In [16]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.impute import SimpleImputer

In [6]:
data = {
    "id":[1,2,3,4,5,6],
    "age":[25,np.nan,30,35,np.nan,100],
    "salary":[50000,60000,np.nan,80000,90000,np.nan],
    "city":["New York","London",np.nan,"Paris","London",np.nan]
}
df = pd.DataFrame(data)
print("original Data:")
display(df)

original Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2    NaN  60000.0    London
2   3   30.0      NaN       NaN
3   4   35.0  80000.0     Paris
4   5    NaN  90000.0    London
5   6  100.0      NaN       NaN

In [7]:
mean_imputer = SimpleImputer(strategy='mean')
df_mean =df.copy()
df_mean[['age','salary']]= mean_imputer.fit_transform(df_mean[['age','salary']])
print("\n Impute Mean Data")
display(df_mean)

 Impute Mean Data

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   47.5  60000.0    London
2   3   30.0  70000.0       NaN
3   4   35.0  80000.0     Paris
4   5   47.5  90000.0    London
5   6  100.0  70000.0       NaN

In [9]:
median_imputer =SimpleImputer(strategy='median')
df_median = df.copy()
df_median[['age','salary']]=median_imputer.fit_transform(df_median[['age','salary']])
print("\n Impute Median  Data")
display(df_median)

 Impute Median  Data

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   32.5  60000.0    London
2   3   30.0  70000.0       NaN
3   4   35.0  80000.0     Paris
4   5   32.5  90000.0    London
5   6  100.0  70000.0       NaN

In [11]:
mode_imputer = SimpleImputer(strategy= 'most_frequent')
df_mode = df.copy()
df_mode[['city']]=mode_imputer.fit_transform(df_mode[['city']])
print("\n Impute Mode Data")
display(df_mode)

 Impute Mode Data

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2    NaN  60000.0    London
2   3   30.0      NaN    London
3   4   35.0  80000.0     Paris
4   5    NaN  90000.0    London
5   6  100.0      NaN    London

In [12]:
df_random =df.copy()

def random_impute(series):
    filled=series.dropna().tolist()
    return series.apply(lambda x:random.choice(filled) if pd.isnull(x) else x )
for col in ['age','salary','city']:
    df_random[col]=random_impute(df_random[col])


print("\n Random  Imputed Data:")
display(df_random)

 Random  Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   25.0  60000.0    London
2   3   30.0  90000.0     Paris
3   4   35.0  80000.0     Paris
4   5  100.0  90000.0    London
5   6  100.0  80000.0    London

In [ ]:
#feature skilling

In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler,RobustScaler

In [18]:
df =pd.DataFrame({'age':[18,22,30,45,60,80],
                  'salary':[20000,25000,40000,60000,120000,1000000]})
print("Original Data:")
print(df)

Original Data:
   age   salary
0   18    20000
1   22    25000
2   30    40000
3   45    60000
4   60   120000
5   80  1000000

In [19]:
#minmax scaler
minmax_scaler =MinMaxScaler()
df_minmax =pd.DataFrame(minmax_scaler.fit_transform(df),columns=df.columns)

print("\n Min Max Scaled Data:")
print(df_minmax)

 Min Max Scaled Data:
        age    salary
0  0.000000  0.000000
1  0.064516  0.005102
2  0.193548  0.020408
3  0.435484  0.040816
4  0.677419  0.102041
5  1.000000  1.000000

In [ ]:
#Standard scaler
standard_scaler =StandardScaler()
df_standard = pd.DataFrame(standard_scaler.fit_transform(df),columns=df.columns)
print("\n Standard Scaled Data")
print(df_standard)

 Standard Scaled Data
        age    salary
0 -1.115270 -0.538353
1 -0.933185 -0.524248
2 -0.569015 -0.481932
3  0.113803 -0.425510
4  0.796621 -0.256247
5  1.707046  2.226289

In [21]:
robust_scaler = RobustScaler()
df_robust = pd.DataFrame(robust_scaler.fit_transform(df),columns= df.columns)
print("\n Robust Scaled Data")
print(df_robust)

 Robust Scaled Data
        age     salary
0 -0.604651  -0.393443
1 -0.480620  -0.327869
2 -0.232558  -0.131148
3  0.232558   0.131148
4  0.697674   0.918033
5  1.317829  12.459016